// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xiFvKXtcHGkN6LLlr34kgR1iZRpgnDw',
    appId: '1:966451611977:web:99a98a9c5c019b37d0b298',
    messagingSenderId: '966451611977',
    projectId: 'fspulast',
    authDomain: 'fspulast.firebaseapp.com',
    storageBucket: 'fspulast.firebasestorage.app',
    measurementId: 'G-00EYWRZSWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgWJRwxqNwyogDcl_sD2EWyUIxQJ0b54k',
    appId: '1:966451611977:android:4505f12100b04922d0b298',
    messagingSenderId: '966451611977',
    projectId: 'fspulast',
    storageBucket: 'fspulast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOP1rD4-16cqqNADCV7-boNLWqZR9D9jw',
    appId: '1:966451611977:ios:02a669fc7af89553d0b298',
    messagingSenderId: '966451611977',
    projectId: 'fspulast',
    storageBucket: 'fspulast.firebasestorage.app',
    iosBundleId: 'com.example.fspulast',
  );
}
